grafana:
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30090
alertmanager:
  enabled: false
prometheus:
  prometheusSpec:
    scrapeInterval: 10s # Częstsze zbieranie metryk, żeby szybciej widzieć efekty chaosu