apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-kill-frontend
  namespace: demo-app
spec:
  schedule: '@every 15s'
  historyLimit: 2
  concurrencyPolicy: 'Allow'
  type: 'PodChaos'
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - demo-app
      labelSelectors:
        app: frontend