apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-one-frontend-pod
  namespace: demo-app
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - demo-app
    labelSelectors:
      app: frontend