apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: backend-memory-stress
  namespace: demo-app
spec:
  mode: one
  selector:
    namespaces:
      - demo-app
    labelSelectors:
      app: backend
  stressors:
    memory:
      workers: 1
      size: "64MB"
  duration: "2m"